alter table OPERATION_OPERATION add constraint FK_OPERATION_OPERATION_ON_ACCOUNT foreign key (ACCOUNT_ID) references OPERATION_ACCOUNT(ID);
create unique index IDX_OPERATION_OPERATION_UK_DATA_ on OPERATION_OPERATION (DATA_) where DELETE_TS is null ;
create index IDX_OPERATION_OPERATION_ON_ACCOUNT on OPERATION_OPERATION (ACCOUNT_ID);
